# config/meta.yml
meta_product_name: "Taste Explorers"
meta_title: "Taste Explorers - Plongez dans les saveurs locales et du monde autour de chez vous !"
meta_description: "Une plateforme qui permet aux utilisateurs de découvrir des cultures culinaires des régions de France ou du monde en organisant des dîners avec des inconnus partageant les mêmes intérêts culinaires dans leur ville"
meta_image: "https://www.taste-explorers.me/images/cover.png"
